[package]
name = "python-bindings"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "python_bindings"
crate-type = ["cdylib"]

[dependencies]
shred-core = { path = "../shred-core" }
shred-automaton = { path = "../shred-automaton" }
shred-generator = { path = "../shred-generator" }
pyo3 = "0.29.0"
